name: APIs Tests on Linux

on:
  push:
    branches:
      - dev

jobs:
  api-tests-on-linux:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Apply pester tests 
      shell: pwsh
      run: | 
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./install.ps1
        Invoke-Pester './Tests/APIs/'  -Passthru
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}