name: APIs Tests on Windows

on:
  push:
    branches:
      - dev

jobs:     
  api-tests-on-windows:
    runs-on: windows-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Apply pester tests 
      shell: pwsh
      run: | 
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./install.ps1
        Invoke-Pester './Tests/APIs/'  -Passthru