name: APIs Tests on MacOS

on:
  push:
    branches:
      - main
      - dev

jobs:
  api-tests-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Test APIs 
      shell: pwsh
      run: ./Scripts/test_APIs.ps1