name: APIs Tests on Windows

on:
  workflow_run:
    workflows: ["Components Tests On Windows"]
    types:
      - completed

jobs:     
  api-tests-on-windows:
    runs-on: windows-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Apply pester tests 
      shell: pwsh
      run: | 
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./install.ps1
        Import-Module PSComputerManagementZp
        $config = New-PesterConfiguration
        $config.Run.PassThru = $true
        $config.Run.Path = './Tests/APIs/'
        $config.Output.Verbosity = "Detailed"
        Invoke-Pester -Configuration $config