name: APIs Tests on Windows

on:
  push:
    branches:
      - dev

jobs:     
  api-tests-on-windows:
    runs-on: windows-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: pip install -r helper/requirements.txt
    - name: Apply pester tests 
      shell: pwsh
      run: | 
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./install.ps1
        Import-Module PSComputerManagementZp
        $config = New-PesterConfiguration
        $config.Run.PassThru = $true
        $config.Run.Path = './Tests/APIs/'
        $config.Output.Verbosity = "Detailed"
        Invoke-Pester -Configuration $config