name: Components Tests on Linux

on:
  push:
    branches:
      - main

jobs:
  component-tests-on-linux:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: pip install -r ./Scripts/etc/requirements.txt
    - name: Apply pester tests 
      shell: pwsh
      run: | 
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./Scripts/install.ps1
        . ./Tests/Helpers/Register.Components.ps1
        $config = New-PesterConfiguration
        $config.Run.PassThru = $true
        $config.Run.Path = './Tests/Components/'
        $config.Output.Verbosity = "Detailed"
        Invoke-Pester -Configuration $config