name: Components Tests on Windows

on:
  push:
    branches:
      - dev

jobs:
  component-tests-on-windows:
    runs-on: windows-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Apply pester tests 
      shell: pwsh
      run: | 
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./install.ps1
        ./Tests/Helpers/Register.Components.ps1
        $config = New-PesterConfiguration
        $config.Run.PassThru = $true
        $config.Run.Path = './Tests/Components/'
        $config.CodeCoverage.Path = "./Module/Private"
        $config.CodeCoverage.Enabled = $true
        $config.Output.Verbosity = "Detailed"
        Invoke-Pester -Configuration $config
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}