name: Components Tests on Linux

on:
  push:
    branches:
      - main
      - dev

jobs:
  component-tests-on-linux:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Test components
      shell: pwsh
      run: ./Scripts/test_components.ps1