name: Components Tests on Linux

on:
  push:
    branches:
      - main
      - dev

jobs:
  component-tests-on-linux:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Test components
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_USER_NAME: ${{ secrets.GH_USER_NAME }}
        GH_REPO_NAME: ${{ secrets.GH_REPO_NAME }}
      run: ./Scripts/test_components.ps1