name: Installation Tests On Windows

on:
  push:
    branches:
      - main
      - dev

jobs:  
  installation-tests-on-windows:
    runs-on: windows-latest  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: install module 
      shell: pwsh
      run: ./Scripts/test_installation.ps1