name: Installation Tests On MacOS

on:
  push:
    branches:
      - dev

jobs:
  installation-tests-on-macos:
    runs-on: macos-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install module 
      shell: pwsh
      run: |
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./install.ps1
        Import-Module PSComputerManagementZp
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}