name: Installation Tests On Windows

on:
  push:
    branches:
      - dev

jobs:  
  installation-tests-on-windows:
    runs-on: windows-latest  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: pip install -r ./Scripts/requirements.txt
    - name: install module 
      shell: pwsh
      run: |
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./Scripts/install.ps1
        Import-Module PSComputerManagementZp