name: Installation Tests On Linux

on:
  push:
    branches:
      - main
      - dev

jobs:
  installation-tests-on-linux:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: install module 
      shell: pwsh
      run: ./Scripts/test_installation.ps1