name: Installation Tests On Windows

on:
  push:
    branches:
      - main
      - test

jobs:  
  installation-tests-on-windows:
    runs-on: windows-latest  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: install module 
      shell: pwsh
      run: |
        $PSVersionTable
        "ErrorActionPreference: $ErrorActionPreference"
        ./install.ps1
        Import-Module PSComputerManagementZp