# name: Pester Tests

# on:
#   push:
#     branches:
#       - main  # 替换为你的主分支名称

# jobs:
#   test:
#     runs-on: windows-latest  # 这里选择运行在 Windows 环境，可以根据需要选择其他环境
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: install module 
#       shell: pwsh
#       run: | 
#         Copy-Item .\..\PSComputerManagementZp C:\Users\runneradmin\Documents\PowerShell\Modules\ -Recurse -Force  
#     - name: Perform Pester tests from EnvTools.Tests.ps1
#       shell: pwsh
#       run: |
#         Invoke-Pester -Path '0.0.1/tests/EnvTools.Tests.ps1' -Passthru
#     - name: Perform Pester tests from PathTools.Tests.ps1
#       shell: pwsh
#       run: |
#         Invoke-Pester -Path '0.0.1/tests/PathTools.Tests.ps1' -Passthru
#     - name: Perform Pester tests from ProxyTools.Tests.ps1
#       shell: pwsh
#       run: |
#         Invoke-Pester -Path '0.0.1/tests/ProxyTools.Tests.ps1' -Passthru