name: Pester Tests

on:
  push:
    branches:
      - main  # 替换为你的主分支名称

jobs:
  test:
    runs-on: windows-latest  # 这里选择运行在 Windows 环境，可以根据需要选择其他环境
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PowerShell
      uses: powershell/powershell

    - name: Run Pester Tests
      run: |
        # 运行 Pester 测试
        Invoke-Pester -Path '0.0.1/tests/EnvTools.Tests.ps1'
        Invoke-Pester -Path '0.0.1/tests/PathTools.Tests.ps1'
        Invoke-Pester -Path '0.0.1/tests/ProxyTools.Tests.ps1'