name: Pester Tests On Windows

on:
  push:
    branches:
      - main  # 替换为你的主分支名称

jobs:
  test:
    runs-on: windows-latest  # 这里选择运行在 Windows 环境，可以根据需要选择其他环境
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: install module 
      shell: pwsh
      run: | 
        ./install.ps1
    - name: do tests in EnvTools.Tests.ps1
      shell: pwsh
      run: |
        Invoke-Pester -Path '0.0.1/tests/EnvTools.Tests.ps1' -Passthru
    - name: do tests in PathTools.Tests.ps1
      shell: pwsh
      run: |
        Invoke-Pester -Path '0.0.1/tests/PathTools.Tests.ps1' -Passthru
    - name: do tests in ProxyTools.Tests.ps1
      shell: pwsh
      run: |
        Invoke-Pester -Path '0.0.1/tests/ProxyTools.Tests.ps1' -Passthru