name: Publish PowerShell Module

on:
  release:
    types: [published]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Build and publish
      shell: pwsh
      run: |
        ./Scripts/build.ps1
        Publish-Module -Path /tmp/PSComputerManagementZp -NuGetApiKey ${{ secrets.NUGET_KEY }} -Verbose
